version: '3'
services:
  mongo:
    image: "healthcheck/mongo"
    ports:
      - "27017:27017"
    logging:
      driver: none
    healthcheck:
      interval: 1s
      retries: 10
  web:
    build: .
    depends_on: 
      - mongo
    ports:
      - "8080:8080"
  