version: '3'
services:
  db:
    image: "healthcheck/mongo"
    ports:
      - "27017:27017"
    expose:
      - 27017
    logging:
      driver: none
    healthcheck:
      interval: 1s
      retries: 10
  web:
    # network_mode: host
    build: .
    depends_on: 
      - db
    ports:
      - "8000:8000"
    expose:
      - 8000
    links:
      - db
    environment: 
      PORT: 8000
      MONGODB_URL: "mongodb://db:27017/notes"
  